name: Testkit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U build wheel setuptools
    - name: Building pefselab
      run: |
        python -m build --sdist
        SDIST=$(python -c "import os;print(os.listdir('./dist')[-1])" 2>&1)
        python -m pip install dist/$SDIST
    - name: Building pipeline
        cd pefselab
        python3 -c "from pefselab.train_swe_pipeline import create_pipeline; create_pipeline()"
    - name: Test with pytest
      run: |
        cd ../
        python3 -m pytest -v
